[project]
name = "251031-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.0.2",
    "langchain>=1.0.3",
    "langchain-openai>=1.0.1",
    "python-dotenv>=1.2.1",
]
